name: firewall-lint

on:
  pull_request:
    paths:
      - firewall/**.go
      - firewall/go.mod
      - firewall/go.sum

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.4'

    - name: Lint firewall
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.57
        working-directory: firewall
        skip-cache: true
        skip-save-cache: true
