name: web-backend-lint

on:
  pull_request:
    paths:
      - web/backend/**.ts
      - web/backend/.eslintrc.cjs

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint backend
        run: |
          cd web/backend/
          npm ci
          npm run lint

