name: web-frontend-build

on:
  push:
    branches:
      - main
    paths:
      - web/frontend/**.html
      - web/frontend/**.ts
      - web/frontend/**.tsx
      - web/frontend/package.json
      - web/frontend/package-lock.json
      - web/frontend/postcss.config.cjs
      - web/frontend/tailwind.config.cjs
      - web/frontend/tsconfig.json
      - web/frontend/tsconfig.node.json
  pull_request:
    paths:
      - web/frontend/**.html
      - web/frontend/**.ts
      - web/frontend/**.tsx
      - web/frontend/package.json
      - web/frontend/package-lock.json
      - web/frontend/postcss.config.cjs
      - web/frontend/tailwind.config.cjs
      - web/frontend/tsconfig.json
      - web/frontend/tsconfig.node.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd web/frontend/
          npm ci
          npm run build

      - name: Upload build artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: cerbero-frontend
          path: web/frontend/dist

