name: web-lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint frontend
        run: |
          cd web/frontend/
          npm ci
          npm run lint
      - name: Lint backend
        run: |
          cd web/backend/
          npm ci
          npm run lint
