name: web-frontend-build

on:
  push:
    branches:
      - main
    paths:
      - web/frontend/**
  pull_request:
    paths:
      - web/frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build frontend
        run: |
          cd web/frontend/
          npm ci
          npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cerbero-frontend
          path: web/frontend/dist

